---
title: "Judgments RSA — Statistical Analyses"
output:
  html_notebook:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
    theme: cerulean
  html_document:
    toc: true
    toc_depth: '3'
    df_print: paged
---

```{r}
library(lme4)
library(lmerTest)
```

```{r}
df <- read.csv("~/results/lm_judg_rsa_results.csv")
head(df)
```

```{r}

df$enc_name <- as.factor(df$enc_name)
df$caption_type <- as.factor(df$caption_type)
df$participant <- as.factor(df$participant)
head(df)
```

```{r}
df$enc_name <- relevel(df$enc_name, ref = "Qwen3 Embedding") #setting qwen3 as reference
df$caption_type <- relevel(df$caption_type, ref = "MS COCO") #setting COCO as reference
```


```{r}
lmer_w_embedder <- lmer(rs ~ enc_name + (1 | participant), data = df)
lmer_wo_embedder <- lmer(rs ~ 1 + (1 | participant), data = df)
print(anova(lmer_w_embedder, lmer_wo_embedder))
```
```{r}
lmer_w_embedder_and_caption <- lmer(rs ~ enc_name + caption_type + (1 | participant), data = df)
lmer_w_embedder_wo_caption <- lmer(rs ~ enc_name + 1 + (1 | participant), data = df)
print(anova(lmer_w_embedder_and_caption, lmer_w_embedder_wo_caption))
```

```{r}
lmer_w_interaction <- lmer(rs ~ enc_name * caption_type + (1 | participant), data = df)
print(anova(lmer_w_embedder_and_caption, lmer_w_interaction))
```

```{r}
summary(lmer_w_interaction)
```
